apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-push-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: gilab-push-trigger-binding
      name: gitlab-push-trigger
      template:
        ref: gilab-push-trigger-template