apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: person-name
    type: string
    default: John Doe
    description: Some name
  tasks:
  - name: greetings
    taskRef: 
      name: greetings
    params:
    - name: person-name
      value: $(params.person-name)
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: farewell
    taskRef: 
      name: farewell
    workspaces:
    - name: output
      workspace: shared-workspace
    runAfter:
    - greetings