apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-jbosseap
spec:
  params:
    - name: PAYLOAD
      description: Payload enviado pelo GitLab.
    - name: GIT_CLONE_URL
      description: >-
        URL usada para a operação de git clone.
    - name: GIT_BRANCH
      description: Branch git usada no git clone.
    - name: JBOSS_EAP7_SERVER_GROUP
      description: Server Group usado para deploy no JBoss EAP 7.
    - name: DEPLOYED_ARTIFACT_PATH
      description: Caminho do artefato que vai ser implantado.
  tasks:
    - name: echo-payload
      params:
        - name: PAYLOAD
          value: "$(params.PAYLOAD)"
      taskRef:
        kind: Task
        name: echo-payload-task
    - name: git-clone
      params:
        - name: url
          value: "$(params.GIT_CLONE_URL)"
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: "$(params.GIT_BRANCH)"
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      runAfter:
        - echo-payload
    - name: verify-cloned-repo
      taskRef:
        kind: Task
        name: ls-task
      runAfter:
        - git-clone
      workspaces:
        - name: workspace
          workspace: shared-workspace
    - name: maven-build
      runAfter:
        - verify-cloned-repo
      taskRef:
        kind: ClusterTask
        name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - clean
            - package
            - '-DskipTests'
        - name: CONTEXT_DIR
          value: .
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: deploy
      params:
        - name: SERVER_GROUP
          value: $(params.JBOSS_EAP7_SERVER_GROUP)
        - name: DEPLOYED_ARTIFACT_PATH
          value: $(params.DEPLOYED_ARTIFACT_PATH)
        - name: CONNECTION_DATA_SECRET_NAME
          value: "jboss-eap7-connection-data"
      taskRef:
        kind: Task
        name: jboss-eap7-deploy
      runAfter:
        - maven-build
      workspaces:
        - name: workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: maven-settings